### ISSUE TITLE
Dominobackup on Linux Dominoserver terminates with an error

### ISSUE THREAD

**Issue by pcEnte-net** [HCL-TECH-SOFTWARE/domino-backup#15]
**HCL Product Version**
12.0.2

**Describe the bug**
Hey there, at the moment we are trying to implement the dominobackup integration with Veeam for our Linux-based Dominoservers. 

OS (Dominoserver): SLES 15
Veeam on Windows Server 2016, Version 12.1.1.56

When a backupjob is started from our Veeam server an error occurs processing the deltafiles on the Dominoserver. Before that, the databases appear to be successfully brought into a consistent, backupable state and in the "Backup and Restore" application on the Dominoserver the triggered backupjob does show up (first as "pending", later as "error"). The backup result on the Veeam server is "failed" as well. Here is an excerpt from the log while the backup job was running:

> load backup -s
01.02.2024 17:20:53   Backup: Domino Database Backup
01.02.2024 17:20:53   Backup: Started
01.02.2024 17:20:53   Backup: Pruning backups
01.02.2024 17:20:53   Backup: BackupNode: [d2-l-ibmweb-01], BackupName: [default], Translog Mode: [CIRCULAR],  Backup Mode: [SNAP]
01.02.2024 17:20:53   Backup: LastBackupTime: 
01.02.2024 17:20:53   Backup: Starting backup for 170 database(s) [*SnapShotMode*]
01.02.2024 17:20:53   Backup: Creating Snapshot
01.02.2024 17:22:57   Backup: Capturing changes in 170 database(s) [*SnapShotMode*]
01.02.2024 17:22:57   Backup: Empty OS Level Command!
01.02.2024 17:22:57   Backup: Error Running Backup Command Database DeltaFile [internet/iwan_web.nsf] File: [/local/notesdata/internet/iwan_web.nsf.DELTA]
: File cannot be created
01.02.2024 17:22:57   Backup: Empty OS Level Command!
01.02.2024 17:22:57   Backup: Error Running Backup Command Database DeltaFile [internet/iwan.nsf] File: [/local/notesdata/internet/iwan.nsf.DELTA]
: File cannot be created
01.02.2024 17:22:57   Backup: Empty OS Level Command!
01.02.2024 17:22:57   Backup: Error Running Backup Command Database DeltaFile [ddm.nsf] File: [/local/notesdata/ddm.nsf.DELTA]
: File cannot be created
01.02.2024 17:22:57   Backup: Empty OS Level Command!
01.02.2024 17:22:57   Backup: Error Running Backup Command Database DeltaFile [log.nsf] File: [/local/notesdata/log.nsf.DELTA]
: File cannot be created
01.02.2024 17:22:58   Backup: Starting Snapshot Backup
01.02.2024 17:22:58   Backup: 
01.02.2024 17:22:58   Backup: --- Backup Summary ---
01.02.2024 17:22:58   Backup: Previous Backup  : 
01.02.2024 17:22:58   Backup: Start Time       : 01.02.2024 17:20:53
01.02.2024 17:22:58   Backup: End Time         : 01.02.2024 17:22:57
01.02.2024 17:22:58   Backup: Runtime          : 00:02:04.568
01.02.2024 17:22:58   Backup: 
01.02.2024 17:22:58   Backup: All              :   170
01.02.2024 17:22:58   Backup: Processed        :   166
01.02.2024 17:22:58   Backup: Excluded         :     0
01.02.2024 17:22:58   Backup: Pending Compact  :     0
01.02.2024 17:22:58   Backup: Compact Retries  :     0
01.02.2024 17:22:58   Backup: Backup Errors    :     4
01.02.2024 17:22:58   Backup: Not Modified     :     0
01.02.2024 17:22:58   Backup: Delta Files      :     0
01.02.2024 17:22:58   Backup: Delta applied    :     0
01.02.2024 17:22:58   Backup: 
01.02.2024 17:22:58   Backup: Total DB Size    :     6,9 GB
01.02.2024 17:22:58   Backup: Total DeltaSize  :     0,0 Bytes
01.02.2024 17:22:58   Backup: Data Rate        :    56,9 MB/sec
01.02.2024 17:22:58   Backup: --- Backup Summary ---
01.02.2024 17:22:58   Backup: 
01.02.2024 17:22:58   Backup: Finished

There are different errors in this log excerpt:
1. "Backup: Empty OS Level Command"!: Does this error affect the success of the backupjob? 
2. "Backup: Error Running Backup Command Database DeltaFile [internet/iwan.nsf] File: [/local/notesdata/internet/iwan.nsf.DELTA]": File cannot be created": It seems like the generation of the deltafiles for the databases that are currently in use fails. Unfortunately, the error that occurs also prevents the backup (at least without a delta applied) from being stored on the Veeam server (backupjob fails and no data is transmitted from the Domino- to the Veeam server). Now the question arises whether all scripts are assigned correctly in the Domino "Backup and Restore" application. I added screenshots from the configuration tabs to this issue. 

**Error Message**
"Backup: Empty OS Level Command"

AND

"Backup: Error Running Backup Command Database DeltaFile [internet/iwan.nsf] File: [/local/notesdata/internet/iwan.nsf.DELTA]"

**Expected behavior**
The backupjob should be successful and the databasesnapshots with applied delta should be stored on the veeam servers repositories. 

**Screenshots**
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/ca1e3d29-916a-4d61-a3cd-71aed9273035)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/ffbb1345-4e8d-4422-823c-24a065920056)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/a55e0c1b-3daa-407f-89b9-945b8b7d92b4)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/072be0c7-bc20-4934-86c4-b1743a6a212e)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/7895c304-ab8b-4fcf-bf51-851773dc95fc)
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/e872e115-c0ec-4e8e-8a71-76c21f5cdc59)

**Desktop (please complete the following information):**
 - OS: SLES 15 for the Dominoserver, Windows Server 2016 for the Veeam server.

**Additional context**
As you can see in the first screenshot the backupjob also fails if there is no delta to create which is interesting.

**Comment by Daniel-Nashed** [comment]
This does not look like a bug. 
You have no backup command specified for the DELTA files as the error message and the log states:

```
01.02.2024 17:22:57 Backup: Error Running Backup Command Database DeltaFile [internet/iwan_web.nsf] File: [/local/notesdata/internet/iwan_web.nsf.DELTA]
: File cannot be created
01.02.2024 17:22:57 Backup: Empty OS Level Command!

```

You need a place where you store the delta files. usually the best any easiest way is a disk location.
I would recommend you try the file command which is the standard for the normal backup integration.
you can copy those settings from the default config. it will copy the delta files to a file location.
It is generally recommended to also backup the deltas. this could be in the next snapshot or you can store it anywhere on a remote share.

I removed the bug label for now unless this is a confirmed issue. right now this looks like a configuration issue. there is no backup command specified for `Backup DB command:` it's the same command for databases and DELTA files.

**Comment by pcEnte-net** [comment]
Hi,
![image](https://github.com/HCL-TECH-SOFTWARE/domino-backup/assets/74569848/9e7f4b42-d38b-45b9-a3fc-d683fef60b6c)
Adding the file command did in fact solve the problem.
Thank you : )

**Comment by Daniel-Nashed** [comment]
Thanks @pcEnte-net for coming back to confirm and great it works for you!
