### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kaaskilde** [HCL-TECH-SOFTWARE/domino-backup#7]
**HCL Product Version**
12.0.1FP1

**Describe the bug**
Running PRUNE on a backup job failed and delete the whole database inventory, restore jobs and logs from the dominobackup.nsf

**Error Message**
[20F0:008B-2048] 07-03-2023 09:18:13   Remote console command issued by Kristian Aaskilde/OpusNeo: load backup -p
[21D4:0002-15B8] 07-03-2023 09:18:16   Backup: Error Running Prune Database Command for database [F:\HCL\Domino\Data\activity.ntf] : File does not exist
[21D4:0002-15B8] 07-03-2023 09:18:17   Backup: Error Running Prune Database Command for database [F:\HCL\Domino\Data\admin4.nsf] : File does not exist
[21D4:0002-15B8] 07-03-2023 09:18:18   Backup: Error Running Prune Database Command for database [F:\HCL\Domino\Data\admin4.ntf] : File does not exist

![image](https://user-images.githubusercontent.com/126585051/223371387-dc404f94-d228-4dce-b48d-0d6b7115f04f.png)

**To Reproduce**
Hi Daniel,
I'm running with the DXL file that you created for S3 and tried running a PRUNE on a INCRE backup to see if it worked with S3, but it did not. It failed on all files because it looked on the server locally and luckily enough not directly the data lib because it looks like it could have delete all the databases.

But not only did the PRUNE command not work with S3 command as shown below, it also deleted the whole database inventory, restore jobs and logs - the only thing left in the dominobackup.nsf is the configuration and global settings documents.

x:= "/"; q:={"}; "aws s3 rm " + q + BackupTargetDir + x + BackupNode + x + BackupMode + x + BackupDateTime + x + FileName + q +" --no-progress 2>&1"

If you need anything else let me know.

I could send you the database if that could help you?

Best regards
Kristian Aaskilde

**Expected behavior**
I expected the PRUNE cmd to work with S3 and when it failed I would have assumed the PRUNE job would go into a failed state not deleting everything in the database.

**Screenshots**
![image](https://user-images.githubusercontent.com/126585051/223373140-95b4b054-9c4d-4252-9efe-05b28eeb96cb.png)
![image](https://user-images.githubusercontent.com/126585051/223373000-2636712a-1170-4a1e-8b93-074bbd54f370.png)

**Desktop (please complete the following information):**
 - OS: Windows Server 2022

**Additional context**

**Comment by Daniel-Nashed** [comment]
Which settings do you have in the configuration for TargetDir? 
The test formula button does not show the real value. it is just intended to test the formula.

The command executed is really the `aws s3 rm .. ` as shown in your dialog. 
And it uses the parameters passed.

What exactly did it do in your case?

The commands all use the same parameter list. So the `rm` should do exactly the same as the backup to remove the data.
Why should it perform a local operation?

We would need to check what the AWS CLI does, if wrong parameters are specified.

The Minio Command Line would perform a local operation without a bucket name.
But your Bucket name should be specified in this style as shown in the configuration:

```
s3://domino-aws-s3/domino-backup/nsf
```


---

The prune should only occur on the backups in the retention period.
If you set that value lower at the beginning for testing, the retention might have removed more backups than you intended.

You did run prune on an incremental backup? What exactly did you do?
Selected an individual backup and marked it to be pruned?
The same prune command would also pure old pending to be deleted backups if the retention time is due as described above.



Can you please describe in more detail what exactly happened. I don't fully what it tried to remove from the local disk and how you found out where it wanted to delete the files locally.

**Comment by Daniel-Nashed** [comment]
Without more information it is impossible to help. If this problem still occurs in some way and you have more details, please re-open this issue. There are no known cases where the prune isn't working as intended.
